### ISSUE TITLE
When i click Apply button，there is sth error

### ISSUE THREAD

**Issue by joelihn** [qurn/xrandr-keystone-helper#1]
xrandr: failed to get size of gamma for output default

warning: output eDP1 not found;ignoring

**Comment by qurn** [comment]
eDP1 was the output i wanted to configure at that time you can change it to your output e.g. VGA1. I'll add a note in the readme.

**Comment by joelihn** [comment]
> eDP1 was the output i wanted to configure at that time you can change it to your output e.g. VGA1. I'll add a note in the readme.

I`m using a dvi-hdmi cable connect my lcd moniter and raspberry pi 3(raspbian).

I dont know what should i change the "eDP1" to?

And there is two warning line at end (look the picture), how can make the apply correctly?

thanks!

![2020-06-14-200501_1920x1080_scrot](https://user-images.githubusercontent.com/8198266/84592732-67446480-ae7a-11ea-9d6a-ab370cc46706.png)
